<?php require ("header.php");?>

<div class="content">
<div class="maincontent">
<div style="background-color:cornsilk;">

<span style="font-family: Georgia, serif;">

<div style="text-align: left; margin-left: 100px; margin-right: 20px">

<p><b>William T. Murphy </b> (National Archives and Records Administration) </p>
<p>“The Unhappy State of American Newsreel Preservation”</p> 
 <br>
<p>Edited transcript of presentation at Orphans of the Storm: Saving “Orphan Films” in the Digital Age, An Orphan Film Symposium, University of South Carolina, Columbia, SC, September 24, 1999.</p> 
<br>
<p>The newsreel is a single reel showing approximately eight to ten subjects, some of which are timely and newsworthy and others, which are usually interesting but of questionable importance. Newsreels were made for exhibition in theaters like short subjects, and they were shown or issued twice weekly. Newsreels were produced in the United States from 1911 to 1967, and their history is admirably described in Raymond Fielding’s book, which is really the standard book on the subject.

When I attended movies in the 1950s and 60s, I recall seeing newsreels with affection and excitement. In the age of television, however, they became an anachronism. The two last surviving newsreels were Hearst News of the Day, which is housed at UCLA, and the Universal newsreel at the National Archives. They were the last two majors. I think as archivists, it may be interesting for you to know that in the period when the fledgling television news industry and the declining newsreel industry overlapped, a period of about 20 years, there is probably a better visual record for newsreels than for television. Television didn’t use videotape until it was introduced by Ampex in 1956. Although they had the kinescope technology, that was used very sparingly, and newscasts were not saved. Newscasts were not saved on a regular basis until 1968, started by Vanderbilt University, then toward the latter part of the 1970s by the networks themselves. They could only do this because of the introduction of the 3⁄4-inch videocassette, which made taping and saving programs economically feasible, but they didn’t use 2-inch quad tape for that purpose.

As Ray Fielding has said, five companies dominated the newsreel industry in the United States, the five majors. They were others, to be sure. Ray mentioned Kinograms. There is also Gaumont, and there were also specialized newsreels like All-American News, which was made for black audiences from the 1940s and through much of the 50s, but in general, the preservation information I am going to give you relates to the five majors.
There are three aspects of the preservation of the American newsreels. One consists of the edited stories. In other words, the finished newsreel is newsreels that were shown to the public, each given volume numbers and issue numbers, and there are negatives, masters, soundtracks, and so on that relate to the finished product. The second aspect, considerably larger, is the unedited footage. The tip of the iceberg if you will, often far more extensive than the edited stories. The third aspect consists of the finding aids, or the documentation created by the newsreel companies, and these include obviously the catalogue cards, the cameraman’s dope sheets, and the continuity sheets -- in other words, the list of stories that went to theater owners. Somewhat like our attitude toward newspapers, I believe there is a consensus that exists that all newsreels should be preserved, all of the edited newsreels at least should be preserved. Unfortunately, this task is not easy to accomplish. The early newsreels have vanished. They have deteriorated; they disappeared or have been destroyed. Pathé started in 1911, Universal in 1912, and Hearst in 1914 -- just to name the most important ones. Of the several thousand newsreels produced prior to 1920, there are only a few dozen left, at least in the United States.
The newsreels from the 1920s fare a little better, but let me give you some examples. During the decade of the 20s, Hearst produced Universal International for Universal, and only 100,000 feet of that whole decade survives at UCLA. That is approximately 16% of the production for the 1920s. Of the outtakes for Hearst International, 0% survives. Some 20s footage exists from Pathé. However, the losses there have been devastating.

Fox newsreels are the most extensive for the 1920s. However, Fox went further than most to destroy the original order of the newsreel. I think you saw yesterday that Fox management decided to cut up all the stories and assign them Dewey decimal classification numbers and file them that way by subject. This was great for stock footage, but not for reconstituting the newsreel so that they can be seen as they were shown to the contemporary audiences. In theory it can be done, but it is an arduous task. One has to locate the titles, the stories, put them in the original order; and this is not easy because many newsreels only exist as fragments.

The Library of Congress newsreel prints deposited for copyright are also very telling. The Library never collected newsreel outtakes but it accepted several thousand release prints for copyright deposit. For the nitrate period prior to 1940, there are virtually no American newsreels in the Library of Congress from the five major companies.

I am going to give you a few numbers here, so bare with me. For World War II, roughly 1940 to 1945, the Library has 7% of Fox and 7% of Paramount, 34% of Hearst and 20% of Universal. For the entire decade of the 1940s, still the age of nitrate, the Library has 4% from Fox and Paramount, 45% from Hearst and 50% from Universal. For the safety-film period, that is after 1950, the Library has 11% from Fox, 16% from Paramount and about 75% from Hearst and Universal. The Library has virtually no Pathé News from any years, nitrate or safety.

The importance of these copyright prints cannot be overstated, even though the original negatives and master positives are lacking. They are, nevertheless, complete with titles and soundtrack with all the combined stories in their original order just as they were seen by contemporary audiences. The cornerstone of the National Archives newsreel collection is Universal Newsreel, which dates from 1929 to 1967. Universal donated essentially what was a library of motion picture negatives. This means that the sound tracks were separated from the picture negatives, the stories and often the titles were separated as small individual rolls, and the components of each newsreel were stored in one or two large film cans. Some years before the National Archives received the Universal library, an executive at Universal decided to throw away all of the separate soundtracks for the nitrate period (1929 - 1950). Evidently the person who made this foolish decision believed that the soundtracks took up too much space and they had no stock footage value. After all, the potential for use of stock footage was the main reason that the newsreel libraries existed long after their production had stopped. From the 1930s and 40s and much of the 50s, Universal newsreels were stored on these small rolls of negative film -- very much like you have seen here at Fox. Only toward the end of their life, 1957-67, did they put together composite negatives, where everything is intact. Universal donated, of course, the 
outtakes for the library, [but] as Ray Fielding mentioned, about 75% of the nitrate outtakes from the Universal library were destroyed in a fire on December 7, 1978 -- a date I shall never forget.

There are two other important collections in public archives: Hearst at UCLA and certainly the Fox collection here at the University of South Carolina. Except for the teens and the 20s, the Hearst collection (which is also a large negative library) appears to be fairly complete. But again, each newsreel must be painstakingly restored from the small rolls, and they you do find that key elements sometimes are missing. For the Fox newsreel library here at USC, Fox gave them the edited stories from 1942-1944 because they were in very bad shape and apparently needed first. They also donated the outtakes from 1919-1934, but I am told there are quite a number of edited stories among those outtakes. The huge balance of the Fox newsreel library is under the ownership of Fox News and it remains (the nitrate and the safety film) in a vault in Ogdensburg, New Jersey, protected by dogs, snakes, and bugs. I can vouch for that.

What I have said so far accounts for three of the five major newsreels in American history. The other two are Pathé Newsreels, also known as Warner-Pathé and RKO-Pathé; and Paramount News, founded in late 20s as a sound newsreel. The owners of Pathé Newsreels donated their library to the Museum of Modern Art in New York some years ago, but MoMA subsequently had to return the collection, realizing that preserving newsreel archives was just not part of their core mission, and that the resources were well beyond their means. In 1963, a stock footage entrepreneur, Sherman Grinberg acquired the Pathé and Paramount newsreel archives, and they remained in his company’s possession for more than thirty years. That library still exists under that name although it has been acquired by a different owner.

At this point, I wanted to describe what is different about preserving newsreels compared to other archival film. First, like all film, newsreels share the problem of nitrate and safety acetate preservation. Both formats are subject to chemical deterioration, particularly under improper storage conditions. Safety film is subject to the vinegar syndrome, where acid eventually destroys both the image and the base of the film. Secondly, like much of the silent cinema, newsreels share devastating losses, as I have said. The first decade of newsreels is virtually wiped out and for the 20s, thank God, we still have a good deal of Fox, but much of that is fragmented. Unlike most feature films, in restoration newsreels have to be assembled. They have to be pieced together and one has to look at the internal evidence in the can plus other documentation to restore newsreels. As a result, I can tell you that very few newsreels have been restored. UCLA has done a few.

A third aspect, which I believe is unique to newsreel, is the challenge of preserving outtakes. Usually this is not much of a factor in film archives. For example, the Library of Congress has a policy against accepting outtakes at the moment, although they have made a few exceptions to that. Newsreel outtakes contain far more footage than the edited story. When we speak of a library such as Universal, which is 27 million feet, only three to four million feet consisted of edited stories. The rest is unedited outtake material. A good average may be ten feet to one, or twenty-to-one for the unedited footage. But outtakes are important. They have significant research value. They contain far more coverage of the topic at hand. The footage is relatively unedited, and it represents a factual source of information. In fact, you can compare the edited footage to the outtake footage and get a sense of how the story was produced, how it evolved, and what some of the editorial considerations were.

Working with outtakes requires a great deal of labor intensive effort, such arranging, organizing, and splicing short pieces of film onto larger reels -- not only for efficient storage but also duplication in the laboratory. There are often a variety of film elements with outtakes. They all require inspection, repair, splicing, cleaning, attaching leaders, synchronizing picture and sound. These tasks should not be taken too lightly. They cost a lot of time. In addition, the skills for working with film like this are disappearing. It is very hard to get people with the proper skills outside of the Los Angeles area.

Another aspect that tends to distinguish newsreel collections from other kinds of film archives is they are generally in poor physical condition, brought on by years of abuse as stock footage. Abusive practices by researchers include the handling and damaging of originals for research and duplication; tab-to-tab printing (printing a section of a reel rather than the whole reel); and others. I’ll give you an example: editors will cut the film and take out the piece that you like and splice it onto other pieces that you like, and the original pieces will never go back to where they came from. So, all of these practices. . . plus the misplacing of labels and putting reels in the wrong cans. If a stock researcher has a bunch of cans, and takes the film reel out of the can, and you have a bunch of open cans, and all those reels look alike. . . . So years and years of these practices has caused a lot of abuse of newsreels.

The third aspect of preserving newsreels concerns the finding aids and the other documentation. These finding aids are important because subject content is everything. In typical film and video archives, I think that the staff tends to be what I have called "title-centric." Everything is based on the title. Their frame of reference for the collection, their movie going habits, all of that comes from a title. But with newsreels, it is all content, and it is essential to have adequate documentation. Fortunately each of the five American newsreel companies carefully catalogued its footage using card stock and Ditto ink copies for the cross reference cards. These catalogues range from a half million to (for Fox) an estimated three million cards. Unfortunately, I can say that none of these libraries aptly used professional library standards in creating these catalogues, and certainly not for the cross-references. I don’t think they had the list of Library of Congress subject terms available to them. Or if they did, they didn’t use it. So, they provide very video- synchronic access to the content. And also, many of the cards represent footage that no longer exists. In other words, even though the footage is gone, they have not been purged. Over the years, the parts have become embrittled and the ink has faded. Fortunately, however, all of the newsreel companies microfilmed their catalogue cards as insurance. None has yet been fully computerized. One of the problems that we encounter with Universal Newsreel is that if we are going to do a computer catalogue, there is no master file. It is just 500,000 cards of cross- references. We would have to build a master file and scan the cards or re-key them in order to create computerized finding aids.

There are two other forms of documentation worth mentioning: the continuity sheets and the cameraman’s dope sheets. The continuity sheets were sent to the theaters to let them know what the content was. If the theater owners wanted to delete stories, they would do that, based on those sheets because some stories may be controversial in certain parts of the country. Many of these continuity sheets have been saved in the copyright records of the Library of Congress, and most of them have been microfilmed as well by various archives. It seems that only Universal and Fox, and some of Paramount saved the cameraman’s dope sheets. Most of those have disappeared.

To go to the last part of this: I want to give you a brief summary of the preservation status of each of the major five collections.

The Universal library in the National Archives is preserved. We have made safety copies of all the film. The nitrate, in fact, is gone. Universal donated its rights and title to the National Archives, so one of the reasons why the Universal collection is so popular is because there are no title fees, and we do not charge commercial license fees at all. We just charge laboratory fees plus a small handling charge. All of the film has been copied to polyester, and after verification the nitrate was destroyed. We were not permitted to keep nitrate film. The vault fire of December 7, 1978, destroyed 75% of the Universal outtakes from the nitrate period and some of the edited stories from World War II. Now we have fine-grain master positives on most of the films, and there are convenient videocassette copies in the research room that can be handled like books. There is self-service allowed on all the material. The continuity sheets and the cameraman’s dope sheets are also available for researchers.

The Hearst collection is in the custody of UCLA. They have a similar card catalogue of about 500,000 items. In addition, the Hearst Corporation donated its rights to the university, but the University, unlike the National Archives, charges essentially commercial rates, and has become a significant source of income for the preservation program at UCLA. Some of the footage at UCLA has been preserved. It has been copied through NEH grants which selected films relating to the coming of World War II, and some special issues of the newsreels have been restored, but I am told that of the ten or eleven million feet of nitrate at UCLA, less than 10% has been copied. We are reaching near the end of the life expectancy of this film and only 10% is done.
The Fox newsreel archives divided between USC and Fox News in New York. At one time, it was said that together the library amounted to 100 million feet. In 1980, Fox decided to donate the footage incrementally to the University of South Carolina, along with the rights and the title. However, the agreement was suspended by Fox in 1984 and never resumed. Today the University has nitrate from 1919 to 1934, plus part of World War II. The donated amount totals about 11 million feet and [7 million feet needs to be copied]. Where the funds will come from, again we don’t know. That situation is very problematic as well.

The other remaining 40 million feet of Fox footage is managed by Fox News, and it is owned by Twentieth Century Fox in Los Angeles. Where Hearst and Universal have catalogue cards of about 500,000 items, just to gauge the size of the Fox collection, there are almost three million catalogue entries. However, this collection has been unavailable to researchers for almost ten years. Forty million feet, not available, in a major American newsreel library. The staff who knew the footage has passed away or retired and the library that was once conveniently located in midtown Manhattan has closed, and the materials have been shipped to New Jersey.


In the mid 1990s, Fox began a project to copy the remaining 40 million feet using two specially engineered videotape recorders set up for something called ID1 format. At the same time, they would make these a digital ID1 copies, BetacamSP and a SuperVHS copies would also be made. Film-to-film copying was deemed far too expensive. In theory this project sounded very impressive because they are going to copy the film, not at NTSC, not even at PAL, but not quite high-definition television; but that resolution is somewhere between PAL and high-definition. So Fox believed that they could keep up with the technology changes and even output to film, if necessary, and get a decent image. However, they only recorded about 60% of the original film resolution, but I guess it is better than nothing. However, they worked at such a rapid pace I am just incredulous about the whole project. In two years, 40 million feet were processed, and that was about three or four years ago when it was finished, and the project has still been kept within the corporation, for reasons known only to the Fox people themselves. Meanwhile I have recently learned, only last week, that Fox has decided to start making footage available to the public again, on a very low-key basis. Officially speaking from Fox, it is now available and open for research.

The original newsreel archives of Paramount and Pathé still remain in the commercial stock footage library, and from the point of view of scholars, they are practically inaccessible because of the high fees for research and duplication. Nevertheless, there are about 24 million feet left for both libraries, Paramount and Pathé, although it is very hard to get accurate figures. Fortunately, the National Archives has a pretty good run of Paramount from 1940 to 1957, but we have very little Pathé.

In closing, let me express a few final thoughts on newsreel preservation. The first decade is irretrievably lost. Second, there is little time left to salvage the edited newsreels from the 20s, basically from Fox and what remains of Pathé. Then third, the same may be said very soon for the 30s and 40s, which are still nitrate. The youngest nitrate, in fact, is almost fifty years old, and I don’t believe any of this nitrate is now stored under conditions that are conducive to long-term preservation. Even the safety film will not be out of harm's way if kept in substandard storage. And fourth, three of the major collections that are the most valuable for the national documentary heritage remain substantially in commercial stock footage libraries. And finally, even for public archives like the University of South Carolina and UCLA, preservation is not assured unless the funding can be found to copy the remaining newsreels.

That is the situation today as best I can describe it. Thank you. </P>

<br>
<hr>
<br>














<script type="text/javascript" src="https://kvxapi.home.nyu.edu/p/141/sp/14100/embedIframeJs/uiconf_id/4422411/partner_id/141"></script><object id="kaltura_player_52f1d73c64599" name="kaltura_player_52f1d73c64599" type="application/x-shockwave-flash" allowFullScreen="true" allowNetworking="all" allowScriptAccess="always" height="402" width="608" xmlns:dc="http://purl.org/dc/terms/" xmlns:media="http://search.yahoo.com/searchmonkey/media/" rel="media:video" resource="https://kvxapi.home.nyu.edu/index.php/kwidget/wid/0_om4ohi5g/uiconf_id/4422411/entry_id/0_2dj8xuph" data="https://kvxapi.home.nyu.edu/index.php/kwidget/wid/0_om4ohi5g/uiconf_id/4422411/entry_id/0_2dj8xuph"><param name="allowFullScreen" value="true" /><param name="allowNetworking" value="all" /><param name="allowScriptAccess" value="always" /><param name="bgcolor" value="#000000" /><param name="flashVars" value="&" /><param name="movie" value="https://kvxapi.home.nyu.edu/index.php/kwidget/wid/0_om4ohi5g/uiconf_id/4422411/entry_id/0_2dj8xuph" /><a href="http://corp.kaltura.com">video platform</a> <a href="http://corp.kaltura.com/technology/video_management">video management</a> <a href="http://corp.kaltura.com/solutions/overview">video solutions</a><a href="http://corp.kaltura.com/technology/video_player">video player</a> <a rel="media:thumbnail" href="https://cdnx.stream.nyu.edu/p/141/sp/14100/thumbnail/entry_id/0_2dj8xuph/version/100000/width/120/height/90/bgcolor/000000/type/2" ></a> <span property="dc:description" content="CAPERUCITA ROJA (Jorge Mendez Delfino, 1933) silent, b/w, 18:34MPEG-4Size: 406 MBDimensions: 720 x 540Coded: H.264Bit rate: 2,912"></span> <span property="media:title" content="Caperucita_Roja_1933"></span> <span property="media:width" content="608"></span> <span property="media:height" content="402"> </span><span property="media:type" content="application/x-shockwave-flash"></span> <span property="media:duration" content="18:34"></span></object>

<br><br>
<p>and &nbsp;. . . .</p>




   
   
   
   </span> </div> 
<br >* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *<br></div>
<div style="clear:both"></div>			

</div><!-- end maincontent-->            
</div><!--end content-->    
<?php require ("footer.php");?>








